// admin
export let POST_ADMIN_PENDING = "POST_ADMIN_PENDING"
export let POST_ADMIN_SUCCESS = "POST_ADMIN_SUCCESS"
export let POST_ADMIN_ERROR = "POST_ADMIN_ERRRO"

// Voter
export let POST_USER_CREATE_PENDING = "POST_USER_CREATE_PENDING"
export let POST_USER_CREATE_SUCCESS = "POST_USER_CREATE_SUCCESS"
export let POST_USER_CREATE_ERROR = "POST_USER_CREATE_ERROR"

export let GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING"
export let GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS"
export let GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR"

export let DELETE_USER_PENDING = "DELETE_USER_PENDING"
export let DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export let DELETE_USER_ERROR = "DELETE_USER_ERROR"

// party
export let POST_CREATE_PARTY_PENDING = "POST_CREATE_PARTY_PENDING"
export let POST_CREATE_PARTY_SUCCESS = "POST_CREATE_PARTY_SUCCESS"
export let POST_CREATE_PARTY_ERROR = "POST_CREATE_PARTY_ERROR"

export let GET_PARTY_LIST_PENDING = "GET_PARTY_LIST_PENDING"
export let GET_PARTY_LIST_SUCCESS = "GET_PARTY_LIST_SUCCESS"
export let GET_PARTY_LIST_ERROR = "GET_PARTY_LIST_ERROR"

export let DELETE_PARTY_PENDING = " DELETE_PARTY_PENDING"
export let DELETE_PARTY_SUCCESS = " DELETE_PARTY_SUCCESS"
export let DELETE_PARTY_ERROR = " DELETE_PARTY_ERROR"

// election
export let POST_ELECTION_CREATE_PENDING = "POST_ELECTION_CREATE_PENDING"
export let POST_ELECTION_CREATE_SUCCESS = "POST_ELECTION_CREATE_SUCCESS"
export let POST_ELECTION_CREATE_ERROR = "POST_ELECTION_CREATE_ERROR"

export let GET_ELECTION_LIST_PENDING = "GET_ELECTION_LIST_PENDING"
export let GET_ELECTION_LIST_SUCCESS = "GET_ELECTION_LIST_SUCCESS"
export let GET_ELECTION_LIST_ERROR = "GET_ELECTION_LIST_ERROR"

export let DELETE_ELECTION_PENDING = "DELETE_ELECTION_PENDING"
export let DELETE_ELECTION_SUCCESS = "DELETE_ELECTION_SUCCESS"
export let DELETE_ELECTION_ERROR = "DELETE_ELECTION_ERROR"

// party connection
export let POST_PARTYLIST_CREATE_PENDING = "POST_PARTYLIST_CREATE_PENDING"
export let POST_PARTYLIST_CREATE_SUCCESS = "POST_PARTYLIST_CREATE_SUCCESS"
export let POST_PARTYLIST_CREATE_ERROR = "POST_PARTYLIST_CREATE_ERROR"

export let GET_PARTYLIST_LIST_PENDING = "GET_PARTYLIST_LIST_PENDING"
export let GET_PARTYLIST_LIST_SUCCESS = "GET_PARTYLIST_LIST_SUCCESS"
export let GET_PARTYLIST_LIST_ERROR = "GET_PARTYLIST_LIST_ERROR"

export let DELETE_PARTYLIST_PENDING = "DELETE_PARTYLIST_PENDING"
export let DELETE_PARTYLIST_SUCCESS = "DELETE_PARTYLIST_SUCCESS"
export let DELETE_PARTYLIST_ERROR = "DELETE_PARTYLIST_ERROR"

// vote
export let POST_VOTE_CREATE_PENDING = "POST_VOTE_CREATE_PENDING"
export let POST_VOTE_CREATE_SUCCESS = "POST_VOTE_CREATE_SUCCESS"
export let POST_VOTE_CREATE_ERROR = "POST_VOTE_CREATE_ERROR"

export let GET_VOTE_LIST_PENDING = "GET_VOTE_LIST_PENDING"
export let GET_VOTE_LIST_SUCCESS = "GET_VOTE_LIST_SUCCESS"
export let GET_VOTE_LIST_ERROR= "GET_VOTE_LIST_ERROR"

export let DELETE_VOTE_PENDING = "DELETE_VOTE_PENDING"
export let DELETE_VOTE_SUCCESS = "DELETE_VOTE_SUCCESS"
export let DELETE_VOTE_ERROR = "DELETE_VOTE_ERROR"

// vote count
export let GET_COUNT_PENDING = "GET_COUNT_PENDING"
export let GET_COUNT_SUCCESS = "GET_COUNT_SUCCESS"
export let GET_COUNT_ERROR = "GET_COUNT_ERROR"